//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Solution.Infrastructure.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mobile.Solution.Infrastructure.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        internal static string DialogAttentionTitle {
            get {
                return ResourceManager.GetString("DialogAttentionTitle", resourceCulture);
            }
        }
        
        internal static string DialogErrorTitle {
            get {
                return ResourceManager.GetString("DialogErrorTitle", resourceCulture);
            }
        }
        
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string FreightGroup {
            get {
                return ResourceManager.GetString("FreightGroup", resourceCulture);
            }
        }
        
        internal static string FromStation {
            get {
                return ResourceManager.GetString("FromStation", resourceCulture);
            }
        }
        
        internal static string Gu12Rep {
            get {
                return ResourceManager.GetString("Gu12Rep", resourceCulture);
            }
        }
        
        internal static string InitialPlan {
            get {
                return ResourceManager.GetString("InitialPlan", resourceCulture);
            }
        }
        
        internal static string OperativePlan {
            get {
                return ResourceManager.GetString("OperativePlan", resourceCulture);
            }
        }
        
        internal static string ParkProfitReport {
            get {
                return ResourceManager.GetString("ParkProfitReport", resourceCulture);
            }
        }
        
        internal static string PlanFactReport {
            get {
                return ResourceManager.GetString("PlanFactReport", resourceCulture);
            }
        }
        
        internal static string Recip {
            get {
                return ResourceManager.GetString("Recip", resourceCulture);
            }
        }
        
        internal static string RwDayRep {
            get {
                return ResourceManager.GetString("RwDayRep", resourceCulture);
            }
        }
        
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        internal static string ToStation {
            get {
                return ResourceManager.GetString("ToStation", resourceCulture);
            }
        }
        
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        internal static string AnyPeriod {
            get {
                return ResourceManager.GetString("AnyPeriod", resourceCulture);
            }
        }
        
        internal static string FirstTriad {
            get {
                return ResourceManager.GetString("FirstTriad", resourceCulture);
            }
        }
        
        internal static string SecondTriad {
            get {
                return ResourceManager.GetString("SecondTriad", resourceCulture);
            }
        }
        
        internal static string ThirdTriad {
            get {
                return ResourceManager.GetString("ThirdTriad", resourceCulture);
            }
        }
        
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        internal static string CurrentPeriod {
            get {
                return ResourceManager.GetString("CurrentPeriod", resourceCulture);
            }
        }
        
        internal static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        internal static string EtranType {
            get {
                return ResourceManager.GetString("EtranType", resourceCulture);
            }
        }
        
        internal static string RzdType {
            get {
                return ResourceManager.GetString("RzdType", resourceCulture);
            }
        }
        
        internal static string Arbitrary {
            get {
                return ResourceManager.GetString("Arbitrary", resourceCulture);
            }
        }
        
        internal static string NextDay {
            get {
                return ResourceManager.GetString("NextDay", resourceCulture);
            }
        }
        
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        internal static string Weights {
            get {
                return ResourceManager.GetString("Weights", resourceCulture);
            }
        }
        
        internal static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        internal static string HistogramChart {
            get {
                return ResourceManager.GetString("HistogramChart", resourceCulture);
            }
        }
        
        internal static string DailyHistogramChart {
            get {
                return ResourceManager.GetString("DailyHistogramChart", resourceCulture);
            }
        }
        
        internal static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        internal static string LinearChart {
            get {
                return ResourceManager.GetString("LinearChart", resourceCulture);
            }
        }
        
        internal static string ArbitraryDate {
            get {
                return ResourceManager.GetString("ArbitraryDate", resourceCulture);
            }
        }
    }
}
